Damage model
BMann-png/ProjectPascal pull request #12
Opened 2023-04-20 21:21 UTC by Marltonthegreat

2023-04-20 21:23 UTC, BMann-png approved these changes
approved

2023-04-20 21:30 UTC, JoshCole31 approved these changes

2023-04-21 18:32 UTC, zachqpeterson requested changes
Move canDamage to Damage

2023-04-21 21:45 UTC, zachqpeterson reviewed
/
V

2023-04-21 21:45 UTC, zachqpeterson approved these changes
Extra good

2023-04-21 22:11 UTC, merged