Shooting
BMann-png/ProjectPascal pull request #7
Opened 2023-04-14 21:25 UTC by zachqpeterson

2023-04-14 21:31 UTC, Marltonthegreat requested changes
Fix clientside projectiles

2023-04-17 19:58 UTC, JoshCole31 commented
goooooood

2023-04-17 19:58 UTC, Marltonthegreat approved these changes

2023-04-17 20:02 UTC, JoshCole31 approved these changes

2023-04-17 20:04 UTC, merged